class MessageKeys:
    LOGIN_SUCCESS = "login_success"
    INVALID_CREDENTIALS = "invalid_credentials"
    PERMISSION_DENIED = "permission_denied"
    USER_NOT_FOUND = "user_not_found"
    BOOK_NOT_FOUND = "book_not_found"
    DUPLICATE_EMAIL = "duplicate_email"
    VALIDATION_ERROR = "validation_error"
    USERNAME_EXISTS = "username_exists"
    LOGIN_SUCCESS = "login_success"
    INVALID_CREDENTIALS = "invalid_credentials"
    USERNAME_EXISTS = "username_exists"
    REGISTER_SUCCESS = "register_success"
    FETCH_SUCCESS = "fetch_success"
    NOT_AUTHENTICATED = "not_authenticated"
    INACTIVE_USER = "Inactive_user"